site_name: document_test
site_url: https://kuamsLab.github.io/document_test/
site_author: Akihisa Nagata
site_description: ''

# Repository
repo_name: KUAMSLabdocument_test
repo_url: https://github.com/KUAMSLab/document_test
edit_uri: ''
docs_dir: docs

theme:
  name: material